import { Lato } from "next/font/google";
import "../app/globals.css";

import Header from "@/components/ui/header.js";
import Footer from "@/components/ui/footer.js";

const latoSans = Lato({
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bienes Raices",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={latoSans.variable}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
