import { Lato } from "next/font/google";
import "../app/globals.css";

const latoSans = Lato({
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bienes Raices",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={latoSans.variable}>
      <body>{children}</body>
    </html>
  );
}
